#!/bin/bash
set -euo pipefail

# Consolidate AWS audit findings into a single GitHub issue report

AUDIT_DATE=$(date -u +"%Y-%m-%d %H:%M UTC")
REPORT_FILE="/tmp/consolidated-audit-report.md"

# Initialize report
cat > "$REPORT_FILE" <<EOF
# AWS Infrastructure Audit — $(date -u +%Y-%m-%d)

**Audit Date:** $AUDIT_DATE

EOF

# Track overall statistics
CRITICAL_COUNT=0
HIGH_COUNT=0
MEDIUM_COUNT=0
LOW_COUNT=0

# Function to extract findings from audit output
extract_findings() {
  local audit_file=$1
  local audit_name=$2
  local status=$3

  echo "" >> "$REPORT_FILE"
  echo "<details>" >> "$REPORT_FILE"
  echo "<summary>📊 $audit_name $([ "$status" != "0" ] && echo "⚠️ FAILED" || echo "✅")</summary>" >> "$REPORT_FILE"
  echo "" >> "$REPORT_FILE"

  if [ -f "$audit_file" ]; then
    echo '```' >> "$REPORT_FILE"
    head -500 "$audit_file" >> "$REPORT_FILE"  # Limit to 500 lines
    echo '```' >> "$REPORT_FILE"
  else
    echo "No output captured." >> "$REPORT_FILE"
  fi

  echo "" >> "$REPORT_FILE"
  echo "</details>" >> "$REPORT_FILE"
}

# Extract key metrics from cost review
if [ -f /tmp/cost-review.txt ]; then
  MONTHLY_COST=$(grep -oP "Current Month.*: \$\K[0-9,]+" /tmp/cost-review.txt | head -1 || echo "N/A")
  WASTE=$(grep -oP "waste.*\$\K[0-9,]+" /tmp/cost-review.txt | head -1 || echo "0")
else
  MONTHLY_COST="N/A"
  WASTE="0"
fi

# Extract critical issues from credentials audit
if [ -f /tmp/credentials-audit.txt ]; then
  CRITICAL_COUNT=$(grep -c "🔴" /tmp/credentials-audit.txt || echo "0")
  HIGH_COUNT=$(grep -c "⚠️" /tmp/credentials-audit.txt || echo "0")
fi

# Extract architecture score
if [ -f /tmp/architecture-review.txt ]; then
  ARCH_SCORE=$(grep -oP "OVERALL SCORE: [A-F]\+ \(\K[0-9]+" /tmp/architecture-review.txt | head -1 || echo "N/A")
else
  ARCH_SCORE="N/A"
fi

# Extract RI savings potential
if [ -f /tmp/reserved-capacity.txt ]; then
  RI_SAVINGS=$(grep -oP "Total Monthly Savings Potential: \$\K[0-9,]+" /tmp/reserved-capacity.txt | head -1 || echo "0")
else
  RI_SAVINGS="0"
fi

# Write executive summary
cat >> "$REPORT_FILE" <<EOF
## Executive Summary

| Metric | Value |
|--------|-------|
| **Monthly Cost** | \$$MONTHLY_COST |
| **Identified Waste** | \$$WASTE/month |
| **RI Savings Opportunity** | \$$RI_SAVINGS/month |
| **Architecture Score** | $ARCH_SCORE/100 |
| **Critical Issues** | $CRITICAL_COUNT 🔴 |
| **High Priority** | $HIGH_COUNT 🟠 |

---

## Priority Findings

### 🔴 Critical Issues (P0)

EOF

# Extract critical findings from each audit
if [ -f /tmp/credentials-audit.txt ]; then
  grep "🔴" /tmp/credentials-audit.txt | head -5 | sed 's/^/- /' >> "$REPORT_FILE" || echo "None found" >> "$REPORT_FILE"
fi

cat >> "$REPORT_FILE" <<EOF

### 🟠 High Priority (P1)

EOF

# Extract high priority findings
if [ -f /tmp/cost-review.txt ]; then
  grep -A5 "Action Items:" /tmp/cost-review.txt | tail -3 | sed 's/^/- [cost] /' >> "$REPORT_FILE" || echo "None found" >> "$REPORT_FILE"
fi

cat >> "$REPORT_FILE" <<EOF

### 🟡 Medium Priority (P2)

EOF

# Extract medium priority findings from architecture review
if [ -f /tmp/architecture-review.txt ]; then
  grep "⚠️" /tmp/architecture-review.txt | head -3 | sed 's/^/- [architecture] /' >> "$REPORT_FILE" || echo "None found" >> "$REPORT_FILE"
fi

cat >> "$REPORT_FILE" <<EOF

---

## Detailed Findings

EOF

# Append full audit outputs as collapsible sections
extract_findings "/tmp/cost-review.txt" "Cost Review" "${COST_STATUS:-0}"
extract_findings "/tmp/credentials-audit.txt" "Credentials Audit" "${CREDS_STATUS:-0}"
extract_findings "/tmp/architecture-review.txt" "Architecture Review" "${ARCH_STATUS:-0}"
extract_findings "/tmp/reserved-capacity.txt" "Reserved Capacity Review" "${RI_STATUS:-0}"

# Add next steps
cat >> "$REPORT_FILE" <<EOF

---

## Next Steps

- [ ] **P0 (Critical):** Address immediately (within 24 hours)
- [ ] **P1 (High):** Review and assign owners this week
- [ ] **P2 (Medium):** Evaluate for next sprint
- [ ] **P3 (Low):** Backlog for future improvements

---

**Generated by:** [aws-comprehensive-audit](https://github.com/ClubReadyAWSDevOps/devops-skills)
**Audit Date:** $AUDIT_DATE
**Workflow Run:** [#${GITHUB_RUN_NUMBER:-N/A}](${GITHUB_SERVER_URL:-https://github.com}/${GITHUB_REPOSITORY:-ClubReadyAWSDevOps/devops-skills}/actions/runs/${GITHUB_RUN_ID:-0})
EOF

echo "✅ Consolidated report written to $REPORT_FILE"
cat "$REPORT_FILE"
